[0.50/0.6x] Update versions (#464)
* bump sbt-osgi version, to allow building on JDK 9+ (#377)

older versions of the plugin get confused by the JDK version number
format change

discovered by the Scala 2.12 community build

(cherry picked from commit 299e4f6b4a7eab93d7479f59007f8868c178a1cf)

* sbt 0.13.18, scala 2.11.12 / 2.12.8

* Add Java 11 (openjdk11) to Travis CI

* sbt-whitesource 0.1.9

... which should work on Java 11.  No

    java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder